### ISSUE TITLE
Multiple matches found

### ISSUE THREAD

**Issue by Olezha** [webjars/webjars-taglib#6]
&lt;wj:locate path="bootstrap.min.css" /&gt; throws exception: org.webjars.MultipleMatchesException: Multiple matches found for bootstrap.min.css.
since I have two bootstrap.min.css files:
/bootstrap/3.2.0-2/css/bootstrap.min.css
/adminlte/2.3.3/bootstrap/css/bootstrap.min.css
So, I need something like &lt;wj:locate prefix="/bootstrap" path="bootstrap.min.css" /&gt; but there other exception: javax.servlet.jsp.JspException: Either one of prefix or path must be set (but not both)

**Comment by jamesward** [comment]
Can you do something like:

```
<wj:locate webjar="bootstrap" path="css/bootstrap.css" />
```

**Comment by Olezha** [comment]
This is a good way. Yes, I try and like it (but without 'css' folder or path to file).
So:
- This is a true answer
- Maybe, this line has chance to be added to README.md
